SYMBOLS = [ '[', ']', '.', ',', '_','+', '-', ':']
MNEM = [ "MOV", "ADD", "DEC", "CMP", "AND", "OR", "INC", "JGE", "MOVSW"]
OPCODE = ["B0", "02", "FE", "38", "20", "80", "FE","7D", "A5"] #inc 40 - ax
DIRECTIVE =  [ "DB", "DW", "DD", "PTR", "WORD", "DWORD", "BYTE"]
REGISTER16 = [ 'AX', 'CX', 'DX', 'BX', 'SP', 'BP', 'SI', 'DI']
REGISTER8 = [ 'AL','CL', 'DL', 'BL','AH',  'CH', 'DH', 'BH']
SEGMENT = [ "ENDS","SEGMENT",'END']
MACRO = [ "MACRO", "ENDM" ]
ID_SEGMENT = ["ES", "CS", "SS", "DS", "FS", 'GS']
NUMBERS_FOR_REG = [ "26h", "2Eh", "36h", "3Eh", "64h", "65h" ]
data_user = list()
lex_table = list()          # for lexical analisys
error_flags = list()        # for indexes of rows in program with error
bytes = list()               # to define bytes
macro_buf = list()          # text in macro 
macro_user = list()         # list of user identifiers using macro
macro_param = list()        # paraments when calling macro
macro_call = list()
macro_fact_param = list()
start_macro = False
data = list()
operands = list()           # table with information about operands
segment_user = list()       # list of user segment identifiers 
table_segment = list()
label_id = list()
label_dict = dict()
label_berofe_assigm = False
user_dict = dict()          # dict contains user nae and it's com.shift used in second_pass
user_type_dict = dict()
active_seg = 0            # for counting segments and check if it opened
segment_flag = False
shift = 0 
shift_array = list()
macro = 0
start_macrol = list()
active_segl = list()
count = 0